### ISSUE TITLE
What files do you have the copyright info for?

### ISSUE THREAD

**Issue by backdaniel** [PauloGSC/free-ebooks#2]
I just wanted those with cc by, gnu fdl, public domain or similar.
It would be useful to have a list of everything by copyright status or just put it in the filename as flags...

**Comment by PauloGSC** [comment]
@backdaniel thank you for your suggestion, I've thinking about that for a while too.

As for now, the repo has around 650 books, none of which has this license/copyright info, since I did not keep track of it while collecting them. Your statement has prompted me to rethink about this situation, and I'll begin gathering the copyright info from the existing books.

Most likely I'll put these data in a single separate file as I gather it, and update the repo whenever I can.

**Comment by PauloGSC** [comment]
@backdaniel I've finished collecting the copyright/license info from the majority of the books. It's all available in the [copyright-list.md](https://github.com/PauloGSC/free-ebooks/blob/master/copyright-list.md) file. Some of the books in the markdown lack the info because I couldn't find it, but, if you know it or want to pursue it, just get in touch with me.

**Comment by backdaniel** [comment]
sweet!
